spring: 
    profiles: 
    active: 
    - dev
    
---
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8001
    
spring.http.encoding.force: true
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
   
mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件
   type-aliases-package: com.ak.springcloud.entity   ##entity所在包
   mapper-locations: classpath:mybatis/mapper/**/*.xml   #mapper映射文件
   
spring:
   profiles: dev
   application:
      name: microservicecloud-config-dept-client 
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
      url: jdbc:mysql://122.51.89.191:3306/cloudDB01?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8    # 数据库名称
      username: root
      password: sdg#$%fgGR122
      dbcp2:
         min-idle: 5                                           # 数据库连接池的最小维持连接数
         initial-size: 5                                       # 初始化连接数
         max-total: 5                                          # 最大连接数
         max-wait-millis: 200                                  # 等待连接获取的最大超时时间
         
         
eureka:
   client: #客户端注册进eureka服务列表内
      service-url: 
         defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
   instance:
      instance-id: microservicecloud-dept8001
      prefer-ip-address: true     #访问路径可以显示IP地址
      
      
info:
   app.name: ak-microservicecloud
   company.name: www.ak.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
        
---
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8001
    
spring.http.encoding.force: true
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
   
mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件
   type-aliases-package: com.ak.springcloud.entity   ##entity所在包
   mapper-locations: classpath:mybatis/mapper/**/*.xml   #mapper映射文件
   
spring:
   profiles: test
   application:
      name: microservicecloud-config-dept-client 
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
      url: jdbc:mysql://122.51.89.191:3306/cloudDB02?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8    # 数据库名称
      username: root
      password: sdg#$%fgGR122
      dbcp2:
         min-idle: 5                                           # 数据库连接池的最小维持连接数
         initial-size: 5                                       # 初始化连接数
         max-total: 5                                          # 最大连接数
         max-wait-millis: 200                                  # 等待连接获取的最大超时时间
         
         
eureka:
   client: #客户端注册进eureka服务列表内
      service-url: 
         defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
   instance:
      instance-id: microservicecloud-dept8001
      prefer-ip-address: true     #访问路径可以显示IP地址
      
      
info:
   app.name: ak-microservicecloud
   company.name: www.ak.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$